#functions --> taking input and providing the output, execute whenever we call
#function == filter .. we. can write functions but we need to write python code..
#we can use default in built function from ansible.

- name: functions
  hosts: local
  connection: local
  tasks:
  - name: default variable
    ansible.builtin.debug:
     msg: "hello, {{ name }}"

